name: dose_tracker
description: "A medication dose tracking app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^2.6.1

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # UUID generation for medication IDs
  uuid: ^4.5.1

  # Date formatting
  intl: ^0.20.2

  # Percent indicator for adherence ring
  percent_indicator: ^4.2.5

  # Scheduled local notifications
  flutter_local_notifications: ^21.0.0

  # Timezone-aware DateTime for zonedSchedule
  timezone: ^0.11.0
  supabase_flutter: ^2.12.4
  flutter_dotenv: ^6.0.1
  firebase_core: ^4.7.0
  firebase_messaging: ^16.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  mocktail: ^1.0.5

flutter:
  uses-material-design: true

  # Assets declaration
  assets:
    - .env
