// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8tcTS2nhc_yMJhR1OJmgzFY0_c_O3Bxw',
    appId: '1:751274060697:web:96d052b8452de1843f8108',
    messagingSenderId: '751274060697',
    projectId: 'dosetrack-3f033',
    authDomain: 'dosetrack-3f033.firebaseapp.com',
    storageBucket: 'dosetrack-3f033.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ0NuM3xbu-hOrhaS9Fyr1DR5DiilOU4s',
    appId: '1:751274060697:ios:792c6f067abc53f43f8108',
    messagingSenderId: '751274060697',
    projectId: 'dosetrack-3f033',
    storageBucket: 'dosetrack-3f033.firebasestorage.app',
    iosBundleId: 'com.example.doseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8tcTS2nhc_yMJhR1OJmgzFY0_c_O3Bxw',
    appId: '1:751274060697:web:656118bd478100e43f8108',
    messagingSenderId: '751274060697',
    projectId: 'dosetrack-3f033',
    authDomain: 'dosetrack-3f033.firebaseapp.com',
    storageBucket: 'dosetrack-3f033.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ0NuM3xbu-hOrhaS9Fyr1DR5DiilOU4s',
    appId: '1:751274060697:ios:792c6f067abc53f43f8108',
    messagingSenderId: '751274060697',
    projectId: 'dosetrack-3f033',
    storageBucket: 'dosetrack-3f033.firebasestorage.app',
    iosBundleId: 'com.example.doseTracker',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKwPAECr-ZntqKTyNIMs1vpXa-GW0ljIo',
    appId: '1:751274060697:android:3614ee0346824b773f8108',
    messagingSenderId: '751274060697',
    projectId: 'dosetrack-3f033',
    storageBucket: 'dosetrack-3f033.firebasestorage.app',
  );

}